language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - tools
  - extra-android-m2repository
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
- touch $HOME/.android/repositories.cfg
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/daemon/
  - $HOME/.gradle/native/
  - $HOME/.android/build-cache/

before_script:
- chmod +x gradlew

script:
- ./gradlew clean build
- ./gradlew test

deploy:
  provider: script
  script: ./gradlew :clean :build
    :core:assembleRelease :core:bintrayUpload
    :amazon-explicit:assembleRelease :amazon-explicit:bintrayUpload
    :amazon-implicit:assembleRelease :amazon-implicit:bintrayUpload
    :facebook-explicit:assembleRelease :facebook-explicit:bintrayUpload
    :facebook-implicit:assembleRelease :facebook-implicit:bintrayUpload
    :github-explicit:assembleRelease :github-explicit:bintrayUpload
    :google-explicit:assembleRelease :google-explicit:bintrayUpload
    :instagram-explicit:assembleRelease :instagram-explicit:bintrayUpload
    :instagram-implicit:assembleRelease :instagram-implicit:bintrayUpload
    :linkedin-explicit:assembleRelease :linkedin-explicit:bintrayUpload
    :microsoft-explicit:assembleRelease :microsoft-explicit:bintrayUpload
    :twitter-implicit:assembleRelease :twitter-implicit:bintrayUpload
    :vk-explicit:assembleRelease :vk-explicit:bintrayUpload
    :vk-implicit:assembleRelease :vk-implicit:bintrayUpload
    :yahoo-explicit:assembleRelease :yahoo-explicit:bintrayUpload
  skip_cleanup: true
  dry-run: false
  on:
    branch: master