language: android

jdk: oraclejdk8

sudo: false

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.0
  - android-28
  - sys-img-armeabi-v7a-android-28
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license" // Accepting license
- chmod +x gradlew // Add permission

script:
- ./gradlew build connectedCheck
- ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew :clean :amazon-explicit:assembleRelease :amazon-explicit:bintrayUpload :amazon-implicit:assembleRelease :amazon-implicit:bintrayUpload :facebook-explicit:assembleRelease :facebook-explicit:bintrayUpload :facebook-implicit:assembleRelease :facebook-implicit:bintrayUpload :github-explicit:assembleRelease :github-explicit:bintrayUpload :google-explicit:assembleRelease :google-explicit:bintrayUpload :instagram-explicit:assembleRelease :instagram-explicit:bintrayUpload :instagram-implicit:assembleRelease :instagram-implicit:bintrayUpload :linkedin-explicit:assembleRelease :linkedin-explicit:bintrayUpload :microsoft-explicit:assembleRelease :microsoft-explicit:bintrayUpload :twitter-implicit:assembleRelease :twitter-implicit:bintrayUpload :vk-explicit:assembleRelease :vk-explicit:bintrayUpload :vk-implicit:assembleRelease :vk-implicit:bintrayUpload :yahoo-explicit:assembleRelease :yahoo-explicit:bintrayUpload
  skip_cleanup: true
  dry-run: false
  on:
    branch: master